### ISSUE TITLE
Password entry

### ISSUE THREAD

**Issue by andyrichardson** [aki77/atom-input-dialog#1]
Am I right to assume that secure password entry (marked out with asterisks) will not be possible with this package? Maybe the _textPattern_ configuration option provides this functionality but there is no description as to what it is or what it does.

I'm wondering if there is a chance of treating this like a react component with an _onKeyPress_ function or similar.

**Comment by aki77** [comment]
Sorry.
This package is not support for password entry.
I think that it is better to create your own dialog.
